//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WelcomeToVietnam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTravelData
    {
        public int ID { get; set; }
        public string username { get; set; }
        public string place { get; set; }
        public Nullable<int> adult { get; set; }
        public Nullable<int> children { get; set; }
        public Nullable<System.DateTime> checkinDate { get; set; }
        public Nullable<System.DateTime> checkoutDate { get; set; }
        public Nullable<int> quantityRoom { get; set; }
        public string Hotel { get; set; }
        public Nullable<int> payment { get; set; }
    }
}
